baseURL = "https://vdshk.github.io"
title = "Hi, I'm Vadim Abzalov 👋"
languageCode = "en-us"
theme = "hugo-theme-hello-friend-ng"

# enable html in markup
[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
startLevel = 1
endLevel = 2
ordered = false

PygmentsCodeFences = true
PygmentsStyle = "borland"

paginate = 10
rssLimit = 10  # Maximum number of items in the RSS feed.

# This message is only used by the RSS template.
copyright = '<a href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank" rel="noopener">CC BY-NC-ND 4.0</a>'

# googleAnalytics = ""
# disqusShortname = ""

archetypeDir = "archetypes"
contentDir = "content"
dataDir = "data"
layoutDir = "layouts"
publishDir = "public"

buildDrafts = false
buildFuture = false
buildExpired = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo = false
enableEmoji = true
enableMissingTranslationPlaceholders = false
disableRSS = false
disableSitemap = false
disable404 = false
disableHugoGeneratorInject = false

[permalinks]
posts = "/posts/:year/:month/:title/"

[author]
name = "Vadim Abzalov"

[blackfriday]
hrefTargetBlank = true

[taxonomies]
tag = "tags"
category = "categories"
series = "series"

[params]
dateform = "Jan 2, 2006"
dateformShort = "Jan 2"
dateformNum = "2006-01-02"
dateformNumTime = "2006-01-02 15:04"

# Metadata mostly used in document's head
description = "Vadim Abzalov's personal blog"
keywords = "Vadim Abzalov, website, homepage, blog"
images = [""]

# Home subtitle of the index page.
homeSubtitle = "I dig in various interesting technical things and write about it"

# Set a background for the homepage
#backgroundImage = "assets/images/background.jpg"

# Prefix of link to the git commit detail page. GitInfo must be enabled.
#gitUrl = ""

# Set disableReadOtherPosts to true in order to hide the links to other posts.
disableReadOtherPosts = false

# Enable theme toggle
# This options enables the theme toggle for the theme.
# Per default, this option is off.
# The theme is respecting the prefers-color-scheme of the operating system.
# With this option on, the page user is able to set the scheme he wants.
enableThemeToggle = false

# Sharing buttons
# There are a lot of buttons preconfigured. If you want to change them,
# generate the buttons here: https://sharingbuttons.io
# and add them into your own `layouts/partials/sharing-buttons.html`
enableSharingButtons = false

# Integrate Javascript files or stylesheets by adding the url to the external assets or by
# linking local files with their path relative to the static folder, e.g. "css/styles.css"
customCSS = []
customJS = []

# Toggle this option need to rebuild SCSS, requires extended version of Hugo
justifyContent = false  # Set "text-align: justify" to .post-content.

# Custom footer
# If you want, you can easily override the default footer with your own content.
[params.footer]
trademark = true
rss = true
copyright = true
author = true

topText = []
bottomText = [
    "Powered by <a href=\"http://gohugo.io\">Hugo</a>"
]

# Colors for favicons
[params.favicon.color]
mask = "#1b1c1d"
msapplication = "#1b1c1d"
theme = "#1b1c1d"

[params.logo]
logoMark = "👨‍💻"
logoText = "Vadim Abzalov is typing..."
logoHomeLink = "/"

# Set true to remove the logo cursor entirely.
#logoCursorDisabled = false

# Set to a valid CSS color to change the cursor in the logo.
logoCursorColor = "#1b1c1d"

# Set to a valid CSS time value to change the animation duration, "0s" to disable.
#logoCursorAnimate = "2s"

# Commento is more than just a comments widget you can embed —
# it’s a return to the roots of the internet.
# An internet without the tracking and invasions of privacy.
# An internet that is simple and lightweight.
# An internet that is focused on interesting discussions, not ads.
# A better internet.
# Uncomment this to enable Commento.
#[params.commento]
#url = ""

# Uncomment this if you want a portrait on your start page
#[params.portrait]
#path = "images/portrait.jpg"
#alt = "Portrait"
#maxWidth = "10em"

# Social icons : https://github.com/vdshk/hugo-theme-hello-friend-ng/blob/master/docs/svgs.md#available-social-icons
[[params.social]]
name = "twitter"
url = "https://twitter.com/__vdshk"

[[params.social]]
name = "instagram"
url = "https://www.instagram.com/__vdshk/"

[[params.social]]
name = "telegram"
url = "https://telegram.me/vdshk42"

[[params.social]]
name = "email"
url = "mailto:vadim.i.abzalov@gmail.com"

[[params.social]]
name = "github"
url = "https://github.com/vdshk"

#[[params.social]]
#name = "linkedin"
#url = "https://www.linkedin.com/"

[languages]
[languages.en]
weight = 1
copyright = '<a href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank" rel="noopener">CC BY-NC-ND 4.0</a>'

[menu]
#[[menu.main]]
#identifier = "about"
#name = "About"
#url = "about/"
[[menu.main]]
identifier = "posts"
name = "Posts"
url = "posts/"